server:
  port: 10800

spring:
  application:
    name: customer
  cloud:
    #注册中心配置
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        prefer-ip-address: true
    #远程调用配置
    stellalou:
      rest:
        enable: true
      rpc:
        enable: true
        port: 2318
        balancer: random