server:
  port: 6000
spring:
  application:
    name: TeacherService
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        prefer-ip-address: true
    stellalou:
      rest:
        enable: true
      rpc:
        enable: true
