server:
  port: 4000
spring:
  application:
    name: provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        prefer-ip-address: true
    stellalou:
      rpc:
        enable: true
